### ISSUE TITLE
Shader Error

### ISSUE THREAD

**Issue by JingchengYang4** [maxartz15/VertexAnimation#11]
Fresh new installation on Unity 2021.2 and 2021.3, shader has issues which prevents animations from working.
<img width="763" alt="截屏2022-04-16 下午10 09 07" src="https://user-images.githubusercontent.com/43139384/163678111-7bb19f6f-6335-4141-b13f-43702d634f8a.png">

After doing some digging, it appears this has do to with the per hybrid instance option.
https://forum.unity.com/threads/shader-graph-shader-produces-strange-error-in-unity-2021-1-16f1.1149599/
Disabling it does make animations work for mono, and the characters do show for example 2 (ecs), however no animations.

**Comment by JingchengYang4** [comment]
It's not exactly an error, for anyone who came across this issue after Unity 2021.1.15, please enable Hybrid Renderer V2 by adding ENABLE_HYBRID_RENDERER_V2 in scripting define symbols. I will make a commit with changes to the readme.

**Comment by maxartz15** [comment]
Cool! I will have a look at the changes soon, maybe the package in general should be upgraded to a newer version.
