### ISSUE TITLE
is flippositionmap used?

### ISSUE THREAD

**Issue by laurentopia** [maxartz15/VertexAnimation#3]
it doesn't highlight in the graph 
![image](https://user-images.githubusercontent.com/26075468/114443021-137dd700-9b82-11eb-83e9-b07da7dedb6d.png)

**Comment by laurentopia** [comment]
found: the feature is toggling something in the VA shader

**Comment by maxartz15** [comment]
> 
> 
> found: the feature is toggling something in the VA shader

Yup, that is correct. FlipPositionMap is mainly used when you have baked PositionMaps that are not generated by the ModelBaker. For example, if you were to export from Houdini, you will need to check this box (as they export from top to bottom instead of bottom to top).
