### ISSUE TITLE
Subscript error

### ISSUE THREAD

**Issue by ghost** [maxartz15/VertexAnimation#7]
Hey, I am using the Editor version 2021.2.6 and i get the following three erros when I open the scene:

"Shader error in 'TAO/Lit': invalid subscript 'Vector1_967e0c2bcb6e48c2b85b82c6d4c734a4' at line 577"
"Shader error in 'TAO/Lit': invalid subscript 'Vector1_967e0c2bcb6e48c2b85b82c6d4c734a4' at line 2302"
"Shader error in 'TAO/Lit': invalid subscript 'Vector1_967e0c2bcb6e48c2b85b82c6d4c734a4' at line 2975"

**Comment by maxartz15** [comment]
Maybe re-importing the shader helps and/or opening the file and saving it again.

**Comment by ghost** [comment]
I've already tried that and I've already tried it in other versions and the last version I tried and it worked is the 2021.2.3f1.
I have already imported it into a completely new project and the same error occurs.
